config/routes.rb
Rails.application.routes.draw do
  resources :friendsdbs
  get 'home/contact'
  get 'home/about'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendsdb.rb
class Friendsdb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friendsdbs_controller.rb
class FriendsdbsController < ApplicationController
  before_action :set_friendsdb, only: %i[ show edit update destroy ]

  # GET /friendsdbs or /friendsdbs.json
  def index
    @friendsdbs = Friendsdb.all
  end

  # GET /friendsdbs/1 or /friendsdbs/1.json
  def show
  end

  # GET /friendsdbs/new
  def new
    @friendsdb = Friendsdb.new
  end

  # GET /friendsdbs/1/edit
  def edit
  end

  # POST /friendsdbs or /friendsdbs.json
  def create
    @friendsdb = Friendsdb.new(friendsdb_params)

    respond_to do |format|
      if @friendsdb.save
        format.html { redirect_to @friendsdb, notice: "Friendsdb was successfully created." }
        format.json { render :show, status: :created, location: @friendsdb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friendsdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendsdbs/1 or /friendsdbs/1.json
  def update
    respond_to do |format|
      if @friendsdb.update(friendsdb_params)
        format.html { redirect_to @friendsdb, notice: "Friendsdb was successfully updated." }
        format.json { render :show, status: :ok, location: @friendsdb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friendsdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendsdbs/1 or /friendsdbs/1.json
  def destroy
    @friendsdb.destroy
    respond_to do |format|
      format.html { redirect_to friendsdbs_url, notice: "Friendsdb was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendsdb
      @friendsdb = Friendsdb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friendsdb_params
      params.require(:friendsdb).permit(:First_Name, :Last_Name, :Email, :Phone_Number, :Twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendsdbs_helper.rb
module FriendsdbsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/friendsdbs/_form.html.erb
<%= form_with(model: friendsdb) do |form| %>
  <% if friendsdb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendsdb.errors.count, "error") %> prohibited this friendsdb from being saved:</h2>

      <ul>
        <% friendsdb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3" >

    <%= form.text_field :First_Name, class:"form-control", placeholder:'First Name' %>
  </div>

  <div class="field mb-3">
   
    <%= form.text_field :Last_Name, class:"form-control", placeholder:'Last Name' %>
  </div>

  <div class="field mb-3">
  
    <%= form.text_field :Email, class:"form-control", placeholder:'name@example.com' %>
  </div>

  <div class="field mb-3">
   
    <%= form.text_field :Phone_Number, class:"form-control", placeholder:'Phone Number' %>
  </div>

  <div class="field mb-3">
  
    <%= form.text_field :Twitter, class:"form-control", placeholder:'Twitter' %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/friendsdbs/edit.html.erb
<h1>Edit Friends</h1>

<%= render 'form', friendsdb: @friendsdb %>
</br>
<%= link_to 'Show', @friendsdb, class:"btn btn-primary" %> 
<%= link_to 'Back', friendsdbs_path, class:"btn btn-primary" %>

app/views/friendsdbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Friends</h1>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendsdbs.each do |friendsdb| %>
      <tr>
        <td><%= friendsdb.First_Name %></td>
        <td><%= friendsdb.Last_Name %></td>
        <td><%= friendsdb.Email %></td>
        <td><%= friendsdb.Phone_Number %></td>
        <td><%= friendsdb.Twitter %></td>
        <td><%= link_to 'Show', friendsdb %></td>
        <td><%= link_to 'Edit', edit_friendsdb_path(friendsdb) %></td>
        <td><%= link_to 'Destroy', friendsdb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Friend', new_friendsdb_path, class:"btn btn-primary" %>

app/views/friendsdbs/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friendsdb: @friendsdb %>
</br>
<%= link_to 'Back', friendsdbs_path, class:"btn btn-primary"  %>

app/views/friendsdbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @friendsdb.First_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friendsdb.Last_Name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friendsdb.Email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @friendsdb.Phone_Number %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @friendsdb.Twitter %>
</p>

<%= link_to 'Edit', edit_friendsdb_path(@friendsdb), class:"btn btn-primary" %> 
<%= link_to 'Back', friendsdbs_path, class:"btn btn-primary" %>

app/views/home/_headers.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Friends App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link" %>
          
        </li>
        
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Contact', home_contact_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Add friend', friendsdbs_path, class:"nav-link" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends App</title>
  </head>
  <body>
    

    <div class= "container">


     <br/>
    <%= render 'home/headers' %>
    <br/>
    <%= yield %>

  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>